/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColorTransformer: typeof import('./../components/ColorTransformer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ImgOperator: typeof import('./../components/ImgOperator.vue')['default']
    LanguageTransformer: typeof import('./../components/LanguageTransformer.vue')['default']
    RandomColor: typeof import('./../components/RandomColor.vue')['default']
    RegExpTools: typeof import('./../components/RegExpTools.vue')['default']
  }
}
